// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConvertFiles(arg1:Array<main.FileData>,arg2:string):Promise<string>;

export function SelectDirectory():Promise<string>;

export function SelectFiles():Promise<Array<string>>;
