// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertFiles(arg1:Array<string>,arg2:string):Promise<string>;

export function SelectDirectory():Promise<string>;
